"""Metric normalization to a common per-90 player-season schema (Phase 2).

Output schema (one row per source × player × league × season) — every metric's
formula is documented in docs/data_dictionary.md, generated by write_data_dictionary():

    source, source_player_id, player_name, birth_year, nationality, league, season,
    minutes, position,
    goals_per90, xgoals_per90, xassists_per90, key_passes_per90, xg_xa_per90,
    goals_added_raw_per90, goals_added_above_avg_per90,
    pass_pct_over_expected, share_team_touches
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from src.common.config import PROJECT_ROOT
from src.common.logging import get_logger, log_lineage

log = get_logger("harmonize.metrics")

# metric -> (formula description, source columns)
DATA_DICTIONARY: dict[str, tuple[str, str]] = {
    "minutes": ("sum of minutes_played across a player's league-season rows",
                "asa:minutes_played / fbref:playing_time_min"),
    "position": ("modal general position for the league-season",
                 "asa:general_position / fbref:pos (first listed)"),
    "goals_per90": ("goals / minutes * 90", "asa:goals / fbref:performance_gls"),
    "xgoals_per90": ("xgoals / minutes * 90", "asa:xgoals / fbref:expected_xg"),
    "xassists_per90": ("xassists / minutes * 90", "asa:xassists / fbref:expected_xag"),
    "key_passes_per90": ("key_passes / minutes * 90", "asa:key_passes (fbref: n/a)"),
    "xg_xa_per90": ("(xgoals + xassists) / minutes * 90",
                    "asa:xgoals+xassists / fbref:expected_xg+expected_xag"),
    "goals_added_raw_per90": ("goals_added_raw_total / minutes * 90 — g+ is an "
                              "action-value framework, NOT xG (see metric_glossary.md)",
                              "asa:goals_added_raw_total (fbref: n/a)"),
    "goals_added_above_avg_per90": ("goals_added_above_avg_total / minutes * 90",
                                    "asa:goals_added_above_avg_total (fbref: n/a)"),
    "pass_pct_over_expected": ("pass_completion_percentage - xpass_completion_percentage"
                               " (already a rate; NOT per-90 normalized)",
                               "asa:xpass endpoint (fbref: n/a)"),
    "share_team_touches": ("minutes-weighted mean share of team touches (already a "
                           "rate; NOT per-90 normalized)", "asa:xpass endpoint (fbref: n/a)"),
}

METRIC_COLUMNS = [m for m in DATA_DICTIONARY if m not in ("minutes", "position")]

KEY = ["player_id", "league", "season"]


def _per90(total: pd.Series, minutes: pd.Series) -> pd.Series:
    with np.errstate(divide="ignore", invalid="ignore"):
        rate = total / minutes * 90.0
    return rate.where(minutes > 0)


def _aggregate_player_season(df: pd.DataFrame, sum_cols: list[str]) -> pd.DataFrame:
    """Collapse to one row per player-league-season, summing count columns and
    keeping the modal position."""
    present = [c for c in sum_cols if c in df.columns]
    agg = df.groupby(KEY, as_index=False).agg(
        {**{c: "sum" for c in present},
         "minutes_played": "sum",
         "general_position": lambda s: s.mode().iloc[0] if len(s.mode()) else None})
    return agg


def normalize_asa(xgoals: pd.DataFrame, xpass: pd.DataFrame, goals_added: pd.DataFrame,
                  players: pd.DataFrame) -> pd.DataFrame:
    """ASA endpoints -> unified per-90 schema."""
    xg = _aggregate_player_season(
        xgoals, ["goals", "xgoals", "xassists", "key_passes", "shots", "primary_assists"])
    xg["goals_per90"] = _per90(xg["goals"], xg["minutes_played"])
    xg["xgoals_per90"] = _per90(xg["xgoals"], xg["minutes_played"])
    xg["xassists_per90"] = _per90(xg["xassists"], xg["minutes_played"])
    xg["key_passes_per90"] = _per90(xg["key_passes"], xg["minutes_played"])
    xg["xg_xa_per90"] = _per90(xg["xgoals"] + xg["xassists"], xg["minutes_played"])

    ga = _aggregate_player_season(
        goals_added, ["goals_added_raw_total", "goals_added_above_avg_total"])
    ga["goals_added_raw_per90"] = _per90(ga["goals_added_raw_total"], ga["minutes_played"])
    ga["goals_added_above_avg_per90"] = _per90(ga["goals_added_above_avg_total"],
                                               ga["minutes_played"])

    xp = xpass.copy()
    xp["pass_pct_over_expected"] = (xp["pass_completion_percentage"]
                                    - xp["xpass_completion_percentage"])
    xp["_w"] = xp["minutes_played"].clip(lower=1)
    xp = xp.groupby(KEY, as_index=False).apply(
        lambda g: pd.Series({
            "pass_pct_over_expected": np.average(g["pass_pct_over_expected"], weights=g["_w"]),
            "share_team_touches": np.average(g["share_team_touches"], weights=g["_w"]),
        }), include_groups=False)

    out = xg.merge(ga[KEY + ["goals_added_raw_per90", "goals_added_above_avg_per90"]],
                   on=KEY, how="left")
    out = out.merge(xp, on=KEY, how="left")

    identity = players.drop_duplicates("player_id")[
        ["player_id", "player_name", "birth_date", "nationality"]].copy()
    identity["birth_year"] = pd.to_datetime(
        identity["birth_date"], errors="coerce").dt.year
    out = out.merge(identity[["player_id", "player_name", "birth_year", "nationality"]],
                    on="player_id", how="left")

    unnamed = out["player_name"].isna().sum()
    if unnamed:
        log_lineage("normalize_asa", "kept-with-null-name", int(unnamed),
                    "player_id absent from ASA players identity table")

    out = out.rename(columns={"player_id": "source_player_id",
                              "minutes_played": "minutes",
                              "general_position": "position"})
    out["source"] = "asa"
    return out[["source", "source_player_id", "player_name", "birth_year", "nationality",
                "league", "season", "minutes", "position"] + METRIC_COLUMNS]


def normalize_fbref(fbref: pd.DataFrame) -> pd.DataFrame:
    """FBref standard player-season stats -> unified per-90 schema.
    FBref has no g+ / xPass equivalents; those columns are explicitly NaN."""
    if fbref.empty:
        return pd.DataFrame()
    df = fbref.copy()
    # one row per player-team-season; aggregate over teams within league-season
    df["birth_year"] = pd.to_numeric(df.get("born"), errors="coerce")
    df["_id"] = df.get("id", df["player"].astype(str))
    for col in ["playing_time_min", "performance_gls", "expected_xg", "expected_xag"]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")
        else:
            df[col] = np.nan
    grouped = df.groupby(["_id", "player", "league", "season"], as_index=False).agg(
        minutes=("playing_time_min", "sum"),
        goals=("performance_gls", "sum"),
        xg=("expected_xg", "sum"),
        xag=("expected_xag", "sum"),
        nationality=("nation", "first"),
        position=("pos", "first"),
        birth_year=("birth_year", "first"),
    )
    grouped["position"] = grouped["position"].astype(str).str.split(",").str[0]
    grouped["goals_per90"] = _per90(grouped["goals"], grouped["minutes"])
    grouped["xgoals_per90"] = _per90(grouped["xg"], grouped["minutes"])
    grouped["xassists_per90"] = _per90(grouped["xag"], grouped["minutes"])
    grouped["xg_xa_per90"] = _per90(grouped["xg"] + grouped["xag"], grouped["minutes"])
    for absent in ["key_passes_per90", "goals_added_raw_per90",
                   "goals_added_above_avg_per90", "pass_pct_over_expected",
                   "share_team_touches"]:
        grouped[absent] = np.nan
    grouped = grouped.rename(columns={"_id": "source_player_id", "player": "player_name"})
    grouped["source"] = "fbref"
    return grouped[["source", "source_player_id", "player_name", "birth_year",
                    "nationality", "league", "season", "minutes", "position"]
                   + METRIC_COLUMNS]


def write_data_dictionary() -> Path:
    lines = ["# Data dictionary — normalized per-90 player-season schema", "",
             "Generated by `src/harmonize/metrics.py`. One row per source × player × "
             "league × season in `data/interim/player_seasons.parquet`.", "",
             "| column | formula | source columns |", "|---|---|---|"]
    for metric, (formula, sources) in DATA_DICTIONARY.items():
        lines.append(f"| `{metric}` | {formula} | {sources} |")
    out = PROJECT_ROOT / "docs" / "data_dictionary.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    return out
