"""RUN_REPORT.md - aggregates every phase's key artifact + all review-queue items
(Phase 6). Regenerated by `python -m src report` / `make report`."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

from src.common.config import PROJECT_ROOT, data_path, load_settings
from src.common.logging import get_logger

log = get_logger("report")

ARTIFACTS = [
    ("Phase 1", "Coverage report", "data/outputs/coverage_report.md"),
    ("Phase 1", "ASA API surface", "docs/asa_api_surface.md"),
    ("Phase 1", "Metric glossary (incl. g+)", "docs/metric_glossary.md"),
    ("Phase 1", "Data contracts", "docs/contracts/"),
    ("Phase 2", "Player crosswalk", "data/crosswalk/player_crosswalk.parquet"),
    ("Phase 2", "Crosswalk audit sample (HUMAN REVIEW)", "data/outputs/crosswalk_audit_sample.csv"),
    ("Phase 2", "Unmatched report", "data/outputs/crosswalk_unmatched_report.md"),
    ("Phase 2", "Data dictionary", "docs/data_dictionary.md"),
    ("Phase 3", "Mover set", "data/interim/movers.parquet"),
    ("Phase 3", "Movers summary", "data/outputs/movers_summary.md"),
    ("Phase 4", "League strengths (+CI)", "data/outputs/league_strength.parquet"),
    ("Phase 4", "Calibration diagnostics", "data/outputs/calibration_diagnostics.md"),
    ("Phase 5", "Proof-of-concept verdict (HUMAN REVIEW)", "data/outputs/proof_of_concept.md"),
    ("All", "Decision log", "DECISIONS.md"),
    ("All", "Review queue", "REVIEW_QUEUE.md"),
    ("All", "Data lineage log", "data/outputs/data_lineage.jsonl"),
]


def _key_numbers() -> list[str]:
    lines = []
    interim = data_path("data_interim")
    outputs = data_path("data_outputs")
    try:
        ps = pd.read_parquet(interim / "player_seasons.parquet")
        lines.append(f"- normalized player-seasons: **{len(ps)}** "
                     f"({ps['source'].value_counts().to_dict()})")
    except Exception:
        lines.append("- normalized player-seasons: _not built yet_")
    try:
        moves = pd.read_parquet(interim / "movers.parquet")
        lines.append(f"- qualifying moves: **{len(moves)}** across "
                     f"{moves['person_id'].nunique()} players")
    except Exception:
        lines.append("- qualifying moves: _not built yet_")
    try:
        strengths = pd.read_parquet(outputs / "league_strength.parquet")
        primary = load_settings()["validation"]["primary_metric"]
        sub = strengths[strengths["metric"] == primary].sort_values("strength", ascending=False)
        pretty = ", ".join(f"{r['league']} {r['strength']:.2f}" for _, r in sub.iterrows())
        lines.append(f"- league strengths ({primary}, anchor MLS=1.0): {pretty}")
    except Exception:
        lines.append("- league strengths: _not built yet_")
    try:
        poc_lines = (outputs / "proof_of_concept.md").read_text(encoding="utf-8").splitlines()
        idx = poc_lines.index("## Verdict")
        verdict_line = next(l for l in poc_lines[idx + 1:] if l.strip())
        lines.append(f"- proof-of-concept verdict: {verdict_line}")
    except Exception:
        lines.append("- proof-of-concept verdict: _not produced yet_")
    return lines


def write_run_report() -> Path:
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# RUN REPORT - Cross-League Player Value Translation Engine",
        "",
        f"_Generated {stamp} by `python -m src report`._",
        "",
        "## Key numbers", "",
        *_key_numbers(),
        "",
        "## Artifacts by phase", "",
        "| phase | artifact | path | exists |",
        "|---|---|---|---|",
    ]
    for phase, name, rel in ARTIFACTS:
        exists = "yes" if (PROJECT_ROOT / rel).exists() else "MISSING"
        lines.append(f"| {phase} | {name} | `{rel}` | {exists} |")

    lines += ["", "## Human review queue (verbatim)", ""]
    queue = PROJECT_ROOT / "REVIEW_QUEUE.md"
    if queue.exists():
        lines.append(queue.read_text(encoding="utf-8"))

    out = PROJECT_ROOT / "RUN_REPORT.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    log.info("run report written to %s", out)
    return out
